source 'https://github.com/CocoaPods/Specs.git'

target 'CocoaPlus', :exclusive => true do
  pod "CocoaPlus", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "CocoaPlus", :path => "../"

#  pod 'Quick'
  pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
end
