source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
use_frameworks!

target 'CocoaPlus', :exclusive => true do
  pod "CocoaPlus", :path => "../"
#  pod 'Specta'
#  pod 'Expecta'
#  pod 'FBSnapshotTestCase'
#  pod 'Expecta+Snapshots'
end

target 'Tests', :exclusive => true do
  pod "CocoaPlus", :path => "../"

#  pod 'Quick'
  pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
end
